### ISSUE TITLE
typing amount of members instead of y/n cant kick members

### ISSUE THREAD

**Issue by alice11987** [wenjianmuran/Plan-Statistic#9]
<img width="662" alt="screen shot 2016-11-15 at 11 03 01 am" src="https://cloud.githubusercontent.com/assets/22471669/20291718/23b7cdbe-ab23-11e6-9339-83eb7e3c17ce.png">

as the photo is shown above, I thought I have kicked the members but realized in a while that I failed to do so.

**Comment by wenjianmuran** [comment]
I don't think it is good to do so.

Solution: When user gives it a invalid value, give information and ask user again.

**Comment by wenjianmuran** [comment]
fix #9
